heat_template_version: queens

description: >
  Creates a port on the External network, using a map of IPs per role.
  Each role has a map of IPs in <Role>IPs parameters, with a list of IPs by
  network (lower_name or lower case). For example:
  ControllerIPs:
    external:
    - 1.2.3.4 # First controller
    - 1.2.3.5 # Second controller

parameters:
  ExternalNetName:
    description: The name of the external network.
    default: external
    type: string
  PortName:
    description: Name of the port
    default: ''
    type: string
  FixedIPs:
    description: >
        Control the IP allocation for the VIP port. E.g.
        [{'ip_address':'1.2.3.4'}]
    default: []
    type: json
  ControlPlaneIP: # Here for compatibility with noop.yaml
    description: IP address on the control plane
    default: ''
    type: string
  ControlPlaneNetwork: # Here for compatibility with ctlplane_vip.yaml
    description: The name of the undercloud Neutron control plane
    default: ctlplane
    type: string
  ControlPlaneSubnet: # Here for compatibility with ctlplane_vip.yaml
    description: The name of the undercloud Neutron control plane subnet
    default: ctlplane-subnet
    type: string
  IPPool: # Set in <Role>IPs map, see environments/ips-from-pool-all.yaml
    default: {}
    type: json
  NodeIndex: # First node in the role will get first IP, and so on...
    default: 0
    type: number
  ExternalNetCidr:
    default: 169.47.15.160/27
    description: Cidr for the external network.
    type: string

outputs:
  ip_address:
    description: External network IP
    value: {get_param: [IPPool, {get_param: ExternalNetName}, {get_param: NodeIndex}]}
  ip_address_uri:
    description: External network IP (for compatibility with external_v6.yaml)
    value: {get_param: [IPPool, {get_param: ExternalNetName}, {get_param: NodeIndex}]}
  ip_subnet:
    description: IP/Subnet CIDR for the External network IP
    value:
      list_join:
      - ''
      - - {get_param: [IPPool, {get_param: ExternalNetName}, {get_param: NodeIndex}]}
        - '/'
        - {str_split: ['/', {get_param: ExternalNetCidr}, 1]}
